version: "3.4"
networks:
  main:
services:
  browser:
    image: nextmoose/browser:scratch_05e996af-8b1f-40b7-9c8c-eba269f7d0e1
    privileged: true
    shm_size: "256m"
    environment:
      DISPLAY:
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    networks:
      main:
    command: ["http://cloud9:14918"]
    labels:
      expiry: "${EXPIRY}"
  cloud9:
    image: nextmoose/cloud9:scratch_65de0557-be0d-44ed-bb84-a7dfa908a89a
    networks:
      main:
    environment:
      PROJECT_NAME: "cloud9"
      CLOUD9_PORT: "14918"
    labels:
      expiry: "${EXPIRY}"
  secret-editor.main:
    image: nextmoose/secret-editor:scratch_0aa97a0b-94d1-459d-bda4-6a751defd727
    networks:
      main:
    environment:
      PROJECT_NAME: "secret-editor.main"
      CLOUD9_PORT: "14918"
      GPG_SECRET_KEY:
      GPG2_SECRET_KEY:
      GPG_OWNER_TRUST:
      GPG2_OWNER_TRUST:
      GPG_KEY_ID:
      USER_NAME:
      USER_EMAIL:
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "${SECRETS_ORIGIN_ORGANIZATION}"
      ORIGIN_REPOSITORY: "${SECRETS_ORIGIN_REPOSITORY}"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
    labels:
      expiry: "${EXPIRY}"
  commander.main:
    image: nextmoose/commander:scratch_dd6d1e7f-3841-4ba3-9207-63d3683fd0fa
    networks:
      main:
        aliases:
          - commander.main
    environment:
      PROJECT_NAME: "commander.main"
      CLOUD9_PORT: "14918"
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    labels:
      expiry: "${EXPIRY}"
  github:
    image: nextmoose/github:scratch_b569e7f6-60e5-499d-8ba6-aa9f2185f0e1
    networks:
      main:
    environment:
      PROJECT_NAME: "github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "governor"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "governor"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "governor"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  governor.github:
    image: nextmoose/github:scratch_b569e7f6-60e5-499d-8ba6-aa9f2185f0e1
    networks:
      main:
    environment:
      PROJECT_NAME: "governor.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "governor"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "governor"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "governor"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  secret-editor.github:
    image: nextmoose/github:scratch_b569e7f6-60e5-499d-8ba6-aa9f2185f0e1
    networks:
      main:
    environment:
      PROJECT_NAME: "github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "secret-editor"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "secret-editor"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "secret-editor"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  cloud9.github:
    image: nextmoose/github:scratch_b569e7f6-60e5-499d-8ba6-aa9f2185f0e1
    networks:
      main:
    environment:
      PROJECT_NAME: "cloud9.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "cloud9"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "cloud9"
      ORIGIN_REPOSITORY: "secret-editor"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "cloud9"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  github.github:
    image: nextmoose/github:scratch_b569e7f6-60e5-499d-8ba6-aa9f2185f0e1
    networks:
      main:
    environment:
      PROJECT_NAME: "cloud9.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "github"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "cloud9"
      ORIGIN_REPOSITORY: "github"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "github"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  browser.github:
    image: nextmoose/github:scratch_b569e7f6-60e5-499d-8ba6-aa9f2185f0e1
    networks:
      main:
    environment:
      PROJECT_NAME: "browser.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "browser"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "cloud9"
      ORIGIN_REPOSITORY: "browser"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "browser"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  commander.github:
    image: nextmoose/github:scratch_b569e7f6-60e5-499d-8ba6-aa9f2185f0e1
    networks:
      main:
    environment:
      PROJECT_NAME: "commander.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "commander"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "cloud9"
      ORIGIN_REPOSITORY: "commander"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "commander"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    command: ["--project-name", "commander.github", "--cloud9-port", "14918", "--extension", "--upstream-id-rsa", "${UPSTREAM_ID_RSA}", "--upstream-organization", "rebelplutonium", "--upstream-repository", "commander", "--origin-id-rsa", "${ORIGIN_ID_RSA}", "--origin-organization", "nextmoose", "--origin-repository", "commander", "--report-id-rsa", "${REPORT_ID_RSA}", "--report-organization", "rebelplutonium", "--report-repository", "commander", "--host-name", "github.com", "--host-port", "22", "--user-name", "${USER_NAME}", "--user-email", "${USER_EMAIL}", "--master-branch", "master"]
    labels:
      expiry: "${EXPIRY}"
  gitlab:
    image: gitlab/gitlab-ce:10.1.2-ce.0
    networks:
      main:
        aliases:
          - gitlab
    labels:
      expiry: "${EXPIRY}"







