version: "3.4"
networks:
  main:
services:
  browser:
    image: nextmoose/browser:scratch_05e996af-8b1f-40b7-9c8c-eba269f7d0e1
    privileged: true
    shm_size: "256m"
    environment:
      DISPLAY:
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    network:
      main:
    command: ["http://cloud9:14918"]
  cloud9:
    image: nextmoose/cloud9:scratch_65de0557-be0d-44ed-bb84-a7dfa908a89a
    network:
      main:
        aliases:
          - cloud9
    command: ["--project-name", "cloud9", "--cloud9-port", "14918"]
