version: "3.4"
networks:
  main:
services:
  cloud9:
    image: rebelplutonium/cloud9:0.0.0
    networks:
      main:
    environment:
      PROJECT_NAME: "cloud9"
      CLOUD9_PORT: "14918"
    labels:
      expiry: "${EXPIRY}"
  mysecrets:
    image: nextmoose/secret-editor:scratch_0aa97a0b-94d1-459d-bda4-6a751defd727
    networks:
      main:
    environment:
      PROJECT_NAME: "mysecrets"
      CLOUD9_PORT: "14918"
      GPG_SECRET_KEY:
      GPG2_SECRET_KEY:
      GPG_OWNER_TRUST:
      GPG2_OWNER_TRUST:
      GPG_KEY_ID:
      USER_NAME:
      USER_EMAIL:
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "desertedscorpion"
      ORIGIN_REPOSITORY: "passwordstore"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
    labels:
      expiry: "${EXPIRY}"
  mysecrets.testing:
    image: nextmoose/secret-editor:scratch_6007a52c-0a09-4cf2-b2fc-a782241102aa
    networks:
      main:
    environment:
      PROJECT_NAME: "mysecrets"
      CLOUD9_PORT: "14918"
      GPG_SECRET_KEY:
      GPG2_SECRET_KEY:
      GPG_OWNER_TRUST:
      GPG2_OWNER_TRUST:
      GPG_KEY_ID:
      USER_NAME:
      USER_EMAIL:
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "desertedscorpion"
      ORIGIN_REPOSITORY: "passwordstore"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
    labels:
      expiry: "${EXPIRY}"
  browser:
    image: nextmoose/browser:scratch_05e996af-8b1f-40b7-9c8c-eba269f7d0e1
    privileged: true
    shm_size: "256m"
    environment:
      DISPLAY:
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    networks:
      main:
    command: ["http://hacker:14918"]
    labels:
      expiry: "${EXPIRY}"
  hacker:
    image: rebelplutonium/hacker:0.0.4
    networks:
      main:
    environment:
      PROJECT_NAME: "hacker"
      CLOUD9_PORT: "14918"
      DISPLAY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      GPG_SECRET_KEY:
      GPG2_SECRET_KEY:
      GPG_OWNER_TRUST:
      GPG2_OWNER_TRUST:
      GPG_KEY_ID:
      UPSTREAM_ID_RSA:
      ORIGIN_ID_RSA:
      REPORT_ID_RSA:
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      SECRETS_ORIGIN_ORGANIZATION:
      SECRETS_ORIGIN_REPOSITORY:
      LIEUTENANT_AWS_PRIVATE_KEY:
      LIEUTENANT_AWS_PUBLIC_KEY:
      PAVILLION_2_LIEUTENANT_PRIVATE_KEY:
      PAVILLION_2_LIEUTENANT_PUBLIC_KEY:
      HACKER_2_LIEUTENANT_PRIVATE_KEY:
      HACKER_2_LIEUTENANT_PUBLIC_KEY:
      HACKER_2_PAVILLION_PRIVATE_KEY:
      HACKER_2_PAVILLION_PUBLIC_KEY:
      EXPIRY:
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/tmp/.X11-unix/X0:/tmp/.X11-unix/X0:ro"
      - "/:/srv/host:ro"
      - "/media:/srv/media"
      - "/home:/srv/home"
    labels:
      expiry: "${EXPIRY}"
  governor.github:
    image: rebelplutonium/github:0.0.0
    networks:
      main:
    environment:
      PROJECT_NAME: "governor.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "governor"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "governor"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "governor"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  hacker.github:
    image: rebelplutonium/github:0.0.0
    networks:
      main:
    environment:
      PROJECT_NAME: "hacker.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "hacker"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "hacker"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "hacker"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  secret-editor.github:
    image: rebelplutonium/github:0.0.0
    networks:
      main:
    environment:
      PROJECT_NAME: "secret-editor.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "secret-editor"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "secret-editor"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "secret-editor"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  cloud9.github:
    image: rebelplutonium/github:0.0.0
    networks:
      main:
    environment:
      PROJECT_NAME: "cloud9.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "cloud9"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "cloud9"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "cloud9"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  github.github:
    image: rebelplutonium/github:0.0.0
    networks:
      main:
    environment:
      PROJECT_NAME: "github.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "github"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "nextmoose"
      ORIGIN_REPOSITORY: "github"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "github"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
  browser.github:
    image: rebelplutonium/github:0.0.0
    networks:
      main:
    environment:
      PROJECT_NAME: "browser.github"
      CLOUD9_PORT: "14918"
      UPSTREAM_ID_RSA:
      UPSTREAM_ORGANIZATION: "rebelplutonium"
      UPSTREAM_REPOSITORY: "browser"
      ORIGIN_ID_RSA:
      ORIGIN_ORGANIZATION: "cloud9"
      ORIGIN_REPOSITORY: "browser"
      REPORT_ID_RSA:
      REPORT_ORGANIZATION: "rebelplutonium"
      REPORT_REPOSITORY: "browser"
      HOST_NAME: "github.com"
      HOST_PORT: "22"
      USER_NAME:
      USER_EMAIL:
      MASTER_BRANCH: "master"
    labels:
      expiry: "${EXPIRY}"
