version: "3.4"
networks:
  main:
services:
  browser:
    image: nextmoose/browser:scratch_05e996af-8b1f-40b7-9c8c-eba269f7d0e1
    privileged: true
    shm_size: "256m"
    environment:
      DISPLAY:
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    networks:
      main:
    command: ["http://cloud9:14918"]
  cloud9:
    image: nextmoose/cloud9:scratch_65de0557-be0d-44ed-bb84-a7dfa908a89a
    networks:
      main:
        aliases:
          - cloud9
    command: ["--project-name", "cloud9", "--cloud9-port", "14918"]
  github:
    image: nextmoose/github:scratch_65de0557-be0d-44ed-bb84-a7dfa908a89a
    networks:
      main:
        aliases:
          - github
    command: ["--project-name", "github", "--cloud9-port", "14918", "--extension", "--upstream_id_rsa", "${UPSTREAM_ID_RSA}", "--upstream-organization", "rebelplutonium", "--upstream-repository", "governor", "--origin_id_rsa", "${ORIGIN_ID_RSA}", "--origin-organization", "nextmoose", "--upstream-repository", "governor", "--report_id_rsa", "${REPORT_ID_RSA}", "--report-organization", "rebelplutonium", "--report-repository", "governor", "--host-name", "github.com", "--host-port", "22", "--user-name", "${USER_NAME}", "--user-email", "${USER_EMAIL}"]









