version: "3.4"
networks:
  main:
    external:
      name: ${EXTERNAL_NETWORK_NAME}
services:
  browser:
    image: nextmoose/browser:scratch_05e996af-8b1f-40b7-9c8c-eba269f7d0e1
    privileged: true
    shm_size: "256m"
    environment:
      DISPLAY:
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    networks:
      main:
    command: ["http://governor:16842"]
    labels:
      expiry: "${EXPIRY}"